// Builds the shadcn docs UI (examples/docs-ui) and embeds its output into
// src/serve/docs-ui.generated.ts, so the published package serves the UI with no
// runtime build step and no CDN. Re-run after changing the UI, then commit the result.
import { execSync } from 'node:child_process';
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, extname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const uiDir = join(root, 'examples', 'docs-ui');
const distDir = join(uiDir, 'dist');
const outFile = join(root, 'src', 'serve', 'docs-ui.generated.ts');

execSync('npx vite build', { cwd: uiDir, stdio: 'inherit' });

const TEXT_TYPES = { '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8' };
const BINARY_TYPES = { '.woff2': 'font/woff2', '.woff': 'font/woff', '.svg': 'image/svg+xml' };

const assetsDir = join(distDir, 'assets');
const files = {};
for (const name of readdirSync(assetsDir)) {
  const ext = extname(name);
  const path = join(assetsDir, name);
  if (TEXT_TYPES[ext]) {
    files[name] = { type: TEXT_TYPES[ext], encoding: 'utf8', data: readFileSync(path, 'utf8') };
  } else if (BINARY_TYPES[ext]) {
    files[name] = { type: BINARY_TYPES[ext], encoding: 'base64', data: readFileSync(path).toString('base64') };
  } else {
    throw new Error(`Unexpected docs-ui asset type: ${name}`);
  }
}

const indexPath = join(distDir, 'index.html');
if (!existsSync(indexPath)) throw new Error('vite build produced no index.html');
const indexHtml = readFileSync(indexPath, 'utf8');

const banner = '// GENERATED by scripts/build-docs-ui.mjs from examples/docs-ui. Do not edit by hand.\n';
const body = `export const DOCS_UI_INDEX_HTML = ${JSON.stringify(indexHtml)};\n\nexport const DOCS_UI_FILES: Record<string, { type: string; encoding: 'utf8' | 'base64'; data: string }> = ${JSON.stringify(files)};\n`;
writeFileSync(outFile, banner + body);
console.log(`wrote ${outFile} (${Object.keys(files).length} assets)`);
